/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base.mainProgram;

import base.Main;
import base.accountsHandler.Data;
import base.accountsHandler.User;
import base.mainProgram.Games.GameMenu;

import javax.swing.*;
import java.text.NumberFormat;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    private User loggedUser;
    /**
     * Creates new form Home
     * @param loggedUser
     */
    public Home(User loggedUser) {
        initComponents();
        
        this.loggedUser = loggedUser;
        reloadInfo();
    }

    private void reloadInfo(){
        lblWelcome.setText("Bienvenido, "+loggedUser.getName());
        
        NumberFormat twoDecimalsFormat = NumberFormat.getNumberInstance();
        twoDecimalsFormat.setMaximumFractionDigits(2);
        twoDecimalsFormat.setMinimumFractionDigits(2);
        String formattedBalance = twoDecimalsFormat.format(loggedUser.getBalance());
        lblBalance.setText("Balance: $"+formattedBalance);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnRecharge = new javax.swing.JButton();
        btnModifyData = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblWelcome.setText("Bienvenido (usuario)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 107, 0);
        jPanel2.add(lblWelcome, gridBagConstraints);

        lblBalance.setText("Balance: $00.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 107, 0);
        jPanel2.add(lblBalance, gridBagConstraints);

        btnPlay.setText("Jugar");
        btnPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlay.setMaximumSize(new java.awt.Dimension(150, 40));
        btnPlay.setMinimumSize(new java.awt.Dimension(150, 40));
        btnPlay.setOpaque(true);
        btnPlay.setPreferredSize(new java.awt.Dimension(150, 40));
        btnPlay.addActionListener(this::btnPlayActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 35, 0);
        jPanel2.add(btnPlay, gridBagConstraints);

        btnRecharge.setText("Recargar fondos");
        btnRecharge.addActionListener(this::btnRechargeActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel2.add(btnRecharge, gridBagConstraints);

        btnModifyData.setText("Cambiar datos de usuario");
        btnModifyData.addActionListener(this::btnModifyDataActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
        jPanel2.add(btnModifyData, gridBagConstraints);

        btnBack.setText("Volver");
        btnBack.addActionListener(this::btnBackActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        jPanel2.add(btnBack, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> new GameMenu(loggedUser).setVisible(true));
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnRechargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechargeActionPerformed
        double recharge = 0;
        String entry = JOptionPane.showInputDialog("Ingrese la cantidad a recargar: ");
        try{
            recharge = Double.parseDouble(entry);
        }catch(NumberFormatException e){
            //no need?
        }
        if(recharge > 0){
            JOptionPane.showMessageDialog(this,"(Simulando pago y recarga)...");
            Data.editBalance(loggedUser, recharge);
        }else JOptionPane.showMessageDialog(this,"Ingrese solo números positivos","Error",JOptionPane.ERROR_MESSAGE);
        
        reloadInfo();
    }//GEN-LAST:event_btnRechargeActionPerformed

    private void btnModifyDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyDataActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> new ModifyUserData(loggedUser).setVisible(true));
    }//GEN-LAST:event_btnModifyDataActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModifyData;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRecharge;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
