/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base.mainProgram.Games;

import base.accountsHandler.User;
import base.mainProgram.Games.Roulette.Roulette;
import base.mainProgram.Games.Slots.Slots;
import base.mainProgram.Home;

/**
 *
 * @author User
 */
public class GameMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameMenu.class.getName());
    private final User loggedUser;
    /**
     * Creates new form GameMenu
     * @param loggedUser
     */
    public GameMenu(User loggedUser) {
        initComponents();
        
        this.loggedUser = loggedUser;
    }

    public void closeWindow(){
        this.dispose();
        new Home(loggedUser).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnSlots = new javax.swing.JButton();
        btnRoulette = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnSlots.setText("Slots");
        btnSlots.addActionListener(this::btnSlotsActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnSlots, gridBagConstraints);

        btnRoulette.setText("Ruleta");
        btnRoulette.addActionListener(this::btnRouletteActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnRoulette, gridBagConstraints);

        btnBack.setText("Volver");
        btnBack.addActionListener(this::btnBackActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel1.add(btnBack, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlotsActionPerformed
        this.dispose();
        Slots slotGame = new Slots(loggedUser);
        slotGame.setVisible(true);
    }//GEN-LAST:event_btnSlotsActionPerformed

    private void btnRouletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRouletteActionPerformed
        this.dispose();
        Roulette rouletteGame = new Roulette(loggedUser);
        rouletteGame.setVisible(true);
    }//GEN-LAST:event_btnRouletteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        closeWindow();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRoulette;
    private javax.swing.JButton btnSlots;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
